import Header from "@/components/Layout/Header";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Grocery Mart | Mua và Bán Trên Di Động Hoặc Website",
  description: "Generated by create next app",
};
function layout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <>
      <Header locale={locale} />
      <div className="container">{children}</div>
    </>
  );
}

export default layout;
