import Header from "@/components/Layout/Header";
import { Metadata } from "next";
import MainProvider from "./MainProvider";

export const metadata: Metadata = {
  title: "Grocery Mart | Mua và Bán Trên Di Động Hoặc Website",
  description: "Generated by create next app",
};
function layout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: "vi" | "en" };
}) {
  return (
    <MainProvider locale={locale}>
      <>
        <Header locale={locale} />
        <main className="container p-5 2xl:px-0">{children}</main>
      </>
    </MainProvider>
  );
}

export default layout;
