import Header from "@/components/Layout/Header";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Grocery Mart | Mua và Bán Trên Di Động Hoặc Website",
  description: "Generated by create next app",
};
function layout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: "vi" | "en" };
}) {
  return (
    <>
      <Header locale={locale} />
      <main className="container p-5 2xl:px-0">{children}</main>
    </>
  );
}

export default layout;
